

title: PathFX Benchmark Results
description: A Jekyll theme for documentation
remote_theme: pmarsceill/just-the-docs

search_enabled: true

baseurl: "web_bench" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com



plugins:
  - jekyll-feed


